### PR TITLE
detect just file from shebang as well

### PR DESCRIPTION
**Pull request by danielb2**

### CODE REVIEW

**Comment by danielb2** [comment]
> ```
> '\v^#!/%(\w|[/-])*\w/%(env%(\s+-S)?\s+)?just\s'
> ```

looks like a pretty hairy regexp. I suspect this below is enough if we want it to be more generic. Pretty sure we can rely on `bin` being there no matter what, so it's good to look for

```vim

autocmd BufRead,BufNewFile * if getline(1) =~# '^#!.*/bin/.*just' | setfiletype just | endif
```

**Comment by danielb2** [comment]
> The problem with `#!.*` is that the `.*` matches whitespace. What is the issue with using a hairy regex in this context? Performance?

what's the problem with it matching whitespace? 
readability. it's difficult to see what the regexp is doing. 

> ```
> '^#!\S*/bin/.*just'
> ```

what's the thinking here? performance?. it would be a weird looking shebang that allowed a whitespace before the `bin` was reached, and I don't think it would ever happen.

**Comment by NoahTheDuke** [comment]
> readability. it's difficult to see what the regexp is doing.

I don't think this is worth a simpler regex. Regex is tough and the syntax is full of it. Better to be specific. If you feel it necessary, you can write a comment detailing the regex. But we should be aiming for specificity.

**Comment by danielb2** [comment]
ok. go for it. I'll close this because I think this is taking up too much of my time. I don't know what your regexp is doing, nor why it needs to have `env` in there. It assumes no one is going to directly use the just binary.  so either way, that regexp needs to be fixed. And at this point, i don't know what you're looking for, or what you want.

**Comment by NoahTheDuke** [comment]
No worries, thanks for trying.

**Pull request closed without merging**
